#!/bin/bash

# sudo pip install redis
# sudo pip install flask
commandTip(){
  echo 'please enter the param,the command format is:'
  echo '=============================================='
  echo './lazybones start'
  echo './lazybones stop'
  echo './lazybones install'
  echo './lazybones restart'
  echo '=============================================='
  echo 'if the permission deny ,please execute:'
  echo 'chmod +x ./lazybones'
}
if [ ! -n "$1" ]; then
  commandTip
else
  if [ "$1" = "start" ]; then
    nohup python app.py &> /dev/null &
    cd ./cli
    nohup python main.py &> /dev/null &
  elif [ "$1" = "stop" ]; then
    killall python
  elif [ "$1" = "install" ]; then
    sudo pip install flask
    sudo pip install redis
  elif [ "$1" = "restart" ]; then
    #statements
    ./lazybones stop
    ./lazybones start
  else
    commandTip
  fi
fi
